"""add_payment_tables

Revision ID: 157dc16ad3b7
Revises: f45911f05a7b
Create Date: 2026-06-04 10:55:01.258159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '157dc16ad3b7'
down_revision: Union[str, Sequence[str], None] = 'f45911f05a7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portal_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portal_settings_id'), 'portal_settings', ['id'], unique=False)
    op.create_index(op.f('ix_portal_settings_key'), 'portal_settings', ['key'], unique=True)
    op.create_table('instructor_bank_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_holder_name', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('iban', sa.String(), nullable=True),
    sa.Column('swift_bic', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_instructor_bank_details_id'), 'instructor_bank_details', ['id'], unique=False)
    op.create_table('payment_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_batches_id'), 'payment_batches', ['id'], unique=False)
    op.create_table('payment_letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('instructor_user_id', sa.Integer(), nullable=False),
    sa.Column('letter_date', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'SIGNED', 'PAID', name='paymentletterstatus'), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('signed_pdf_path', sa.String(), nullable=True),
    sa.Column('instructor_signature_data', sa.Text(), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['payment_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instructor_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_letters_id'), 'payment_letters', ['id'], unique=False)
    op.create_index(op.f('ix_payment_letters_instructor_user_id'), 'payment_letters', ['instructor_user_id'], unique=False)
    op.create_table('payment_addons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_letter_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('amount_aed', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['payment_letter_id'], ['payment_letters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_addons_id'), 'payment_addons', ['id'], unique=False)
    op.create_index(op.f('ix_payment_addons_payment_letter_id'), 'payment_addons', ['payment_letter_id'], unique=False)
    op.create_table('payment_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_letter_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.String(), nullable=False),
    sa.Column('workshop_description', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('LEAD_FACILITATOR', 'FACILITATOR', 'ASSISTANT_FACILITATOR', name='sessionrole'), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('compensation_aed', sa.Float(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['payment_letter_id'], ['payment_letters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_sessions_id'), 'payment_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_payment_sessions_payment_letter_id'), 'payment_sessions', ['payment_letter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_sessions_payment_letter_id'), table_name='payment_sessions')
    op.drop_index(op.f('ix_payment_sessions_id'), table_name='payment_sessions')
    op.drop_table('payment_sessions')
    op.drop_index(op.f('ix_payment_addons_payment_letter_id'), table_name='payment_addons')
    op.drop_index(op.f('ix_payment_addons_id'), table_name='payment_addons')
    op.drop_table('payment_addons')
    op.drop_index(op.f('ix_payment_letters_instructor_user_id'), table_name='payment_letters')
    op.drop_index(op.f('ix_payment_letters_id'), table_name='payment_letters')
    op.drop_table('payment_letters')
    op.drop_index(op.f('ix_payment_batches_id'), table_name='payment_batches')
    op.drop_table('payment_batches')
    op.drop_index(op.f('ix_instructor_bank_details_id'), table_name='instructor_bank_details')
    op.drop_table('instructor_bank_details')
    op.drop_index(op.f('ix_portal_settings_key'), table_name='portal_settings')
    op.drop_index(op.f('ix_portal_settings_id'), table_name='portal_settings')
    op.drop_table('portal_settings')
    # ### end Alembic commands ###
