"""Add contract paths to instructor profile

Revision ID: 248615f8d875
Revises: b249629ea9aa
Create Date: 2026-03-14 05:47:45.867645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '248615f8d875'
down_revision: Union[str, Sequence[str], None] = 'b249629ea9aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructor_profiles', sa.Column('contract_path', sa.String(), nullable=True))
    op.add_column('instructor_profiles', sa.Column('signed_contract_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instructor_profiles', 'signed_contract_path')
    op.drop_column('instructor_profiles', 'contract_path')
    # ### end Alembic commands ###
