"""Add instructor role and pass flags

Revision ID: 340af073491a
Revises: c96da226051f
Create Date: 2026-03-04 21:09:57.165601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '340af073491a'
down_revision: Union[str, Sequence[str], None] = 'c96da226051f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add INSTRUCTOR to UserRole enum (Postgres specific)
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'INSTRUCTOR'")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('temp_password_last_set_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'temp_password_last_set_at')
    op.drop_column('users', 'must_change_password')
    # ### end Alembic commands ###
