"""add_instructor_profiles_table

Revision ID: 6297a2147aa3
Revises: 340af073491a
Create Date: 2026-03-09 03:55:45.284160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6297a2147aa3'
down_revision: Union[str, Sequence[str], None] = '340af073491a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('instructor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('profile_photo_path', sa.String(), nullable=True),
    sa.Column('instructor_id', sa.String(), nullable=True),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('front_card_path', sa.String(), nullable=True),
    sa.Column('back_card_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instructor_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_instructor_profiles_id'), 'instructor_profiles', ['id'], unique=False)
    # Cast BOOLEAN -> INTEGER safely on PostgreSQL
    # Must drop default first, then cast type, then restore default
    op.execute("ALTER TABLE users ALTER COLUMN must_change_password DROP DEFAULT")
    op.execute("ALTER TABLE users ALTER COLUMN must_change_password TYPE INTEGER USING must_change_password::integer")
    op.execute("ALTER TABLE users ALTER COLUMN must_change_password SET DEFAULT 0")



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'must_change_password',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_instructor_profiles_id'), table_name='instructor_profiles')
    op.drop_table('instructor_profiles')
    # ### end Alembic commands ###
