"""Add SatKit Training Modules Models

Revision ID: b249629ea9aa
Revises: f8fc56349ea0
Create Date: 2026-03-10 04:57:27.095714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b249629ea9aa'
down_revision: Union[str, Sequence[str], None] = 'f8fc56349ea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_training_modules_id'), 'training_modules', ['id'], unique=False)
    op.create_table('training_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('video_path', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['training_modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_videos_id'), 'training_videos', ['id'], unique=False)
    op.create_table('user_training_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['training_videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_training_progress_id'), 'user_training_progress', ['id'], unique=False)
    op.create_index(op.f('ix_user_training_progress_user_id'), 'user_training_progress', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_training_progress_video_id'), 'user_training_progress', ['video_id'], unique=False)
    op.drop_index('ix_instructor_profiles_id', table_name='instructor_profiles')
    op.drop_table('instructor_profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructor_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('linkedin_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('profile_photo_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('instructor_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('issue_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('front_card_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('back_card_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='instructor_profiles_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='instructor_profiles_pkey'),
    sa.UniqueConstraint('instructor_id', name='instructor_profiles_instructor_id_key'),
    sa.UniqueConstraint('user_id', name='instructor_profiles_user_id_key')
    )
    op.create_index('ix_instructor_profiles_id', 'instructor_profiles', ['id'], unique=False)
    op.drop_index(op.f('ix_user_training_progress_video_id'), table_name='user_training_progress')
    op.drop_index(op.f('ix_user_training_progress_user_id'), table_name='user_training_progress')
    op.drop_index(op.f('ix_user_training_progress_id'), table_name='user_training_progress')
    op.drop_table('user_training_progress')
    op.drop_index(op.f('ix_training_videos_id'), table_name='training_videos')
    op.drop_table('training_videos')
    op.drop_index(op.f('ix_training_modules_id'), table_name='training_modules')
    op.drop_table('training_modules')
    # ### end Alembic commands ###
