"""module_level_submissions

Revision ID: c96da226051f
Revises: 5e61c116f22a
Create Date: 2026-03-04 18:01:16.879147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c96da226051f'
down_revision: Union[str, Sequence[str], None] = '5e61c116f22a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('notes_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_submissions_id'), 'module_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_module_submissions_user_id'), 'module_submissions', ['user_id'], unique=False)
    op.create_table('user_checklist_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('checklist_item_id', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['checklist_item_id'], ['checklist_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_checklist_progress_id'), 'user_checklist_progress', ['id'], unique=False)
    op.create_index(op.f('ix_user_checklist_progress_user_id'), 'user_checklist_progress', ['user_id'], unique=False)
    op.drop_index(op.f('ix_checklist_submissions_id'), table_name='checklist_submissions')
    op.drop_index(op.f('ix_checklist_submissions_user_id'), table_name='checklist_submissions')
    op.drop_table('checklist_submissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_submissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('checklist_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('notes_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('reviewer_admin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['checklist_item_id'], ['checklist_items.id'], name=op.f('checklist_submissions_checklist_item_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_admin_id'], ['users.id'], name=op.f('checklist_submissions_reviewer_admin_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('checklist_submissions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('checklist_submissions_pkey'))
    )
    op.create_index(op.f('ix_checklist_submissions_user_id'), 'checklist_submissions', ['user_id'], unique=False)
    op.create_index(op.f('ix_checklist_submissions_id'), 'checklist_submissions', ['id'], unique=False)
    op.drop_index(op.f('ix_user_checklist_progress_user_id'), table_name='user_checklist_progress')
    op.drop_index(op.f('ix_user_checklist_progress_id'), table_name='user_checklist_progress')
    op.drop_table('user_checklist_progress')
    op.drop_index(op.f('ix_module_submissions_user_id'), table_name='module_submissions')
    op.drop_index(op.f('ix_module_submissions_id'), table_name='module_submissions')
    op.drop_table('module_submissions')
    # ### end Alembic commands ###
