"""add instructor document model

Revision ID: daada8289b96
Revises: 248615f8d875
Create Date: 2026-03-28 17:45:05.564010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daada8289b96'
down_revision: Union[str, Sequence[str], None] = '248615f8d875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructor_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instructor_documents_id'), 'instructor_documents', ['id'], unique=False)
    op.create_index(op.f('ix_instructor_documents_user_id'), 'instructor_documents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instructor_documents_user_id'), table_name='instructor_documents')
    op.drop_index(op.f('ix_instructor_documents_id'), table_name='instructor_documents')
    op.drop_table('instructor_documents')
    # ### end Alembic commands ###
