"""Add LibraryModule model

Revision ID: f8fc56349ea0
Revises: 7e2985a92919
Create Date: 2026-03-10 04:47:54.127661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8fc56349ea0'
down_revision: Union[str, Sequence[str], None] = '7e2985a92919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_library_modules_id'), 'library_modules', ['id'], unique=False)
    
    # 1. Add column as nullable first
    op.add_column('library_resources', sa.Column('module_id', sa.Integer(), nullable=True))
    
    # 2. Setup foreign key
    op.create_foreign_key(None, 'library_resources', 'library_modules', ['module_id'], ['id'], ondelete='CASCADE')
    
    # 3. Create a default module for existing resources
    op.execute(
        "INSERT INTO library_modules (name, description, created_at) VALUES ('General Resources', 'Legacy resources without a module', NOW())"
    )
    
    # 4. Update existing resources to point to this new module
    op.execute(
        "UPDATE library_resources SET module_id = (SELECT id FROM library_modules WHERE name = 'General Resources' LIMIT 1)"
    )
    
    # 5. Alter column to NOT NULL
    op.alter_column('library_resources', 'module_id', nullable=False)
    
    # 6. Drop the old category column
    op.drop_column('library_resources', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library_resources', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'library_resources', type_='foreignkey')
    op.drop_column('library_resources', 'module_id')
    op.drop_index(op.f('ix_library_modules_id'), table_name='library_modules')
    op.drop_table('library_modules')
    # ### end Alembic commands ###
